development:
  adapter: mysql2
  encoding: utf8
  database: wal_storage
  pool: 5
  timeout: 5000
  host: localhost
  username: root     # use user/pass from local mysql set up
  password: abcd1234

production:  
  adapter: mysql2
  encoding: utf8
  database: WAL_STORAGE
  pool: 5
  timeout: 5000
  host:  localhost
  port : 3306
  username: root     # use user/pass from local mysql set up
  password: 012_ighg
  
